create sequence "public"."__raw_logs_id_seq";

create table "public"."__raw_logs" (
    "id" integer not null default nextval('__raw_logs_id_seq'::regclass),
    "timestamp" timestamp without time zone not null default CURRENT_TIMESTAMP,
    "message" text not null,
    "logger_name" character varying(255),
    "application_name" character varying(255),
    "environment" character varying(50),
    "error_code" character varying(50),
    "exception_type" character varying(255),
    "stack_trace" text,
    "execution_time" integer,
    "cpu_usage" numeric(5,2),
    "memory_usage" numeric(10,2),
    "response_time" integer,
    "user_id" character varying(255),
    "session_id" character varying(255),
    "request_id" character varying(255),
    "ip_address" character varying(45),
    "url" text,
    "http_method" character varying(10),
    "service_name" character varying(255),
    "hostname" character varying(255),
    "thread_id" character varying(255),
    "correlation_id" character varying(255),
    "custom_field_1" text,
    "custom_field_2" text,
    "log_level" text
);


create table "public"."__raw_trends" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "html" text,
    "url" text,
    "filters" text
);


create table "public"."legal_documents" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "last_updated" timestamp with time zone default now(),
    "title" text,
    "slug" text,
    "content" text,
    "user_id" uuid
);


create table "public"."repo_trends" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "url" text not null,
    "description" text,
    "language" text,
    "stars" text,
    "__raw_trend_id" bigint,
    "last_validated" timestamp with time zone,
    "forks" text,
    "fullName" text
);


alter table "public"."posts" add column "content_text_only" text;

alter table "public"."users" add column "email" text;

alter table "public"."website_settings" add column "post__settings__wordcloud_stop_words" text[] default '{''a'',''about'',''above'',''after'',''again'',''against'',''all'',''am'',''an'',''and'',''any'',''are'',''aren''''t'',''as'',''at'',''be'',''because'',''been'',''before'',''being'',''below'',''between'',''both'',''but'',''by'',''can''''t'',''cannot'',''could'',''couldn''''t'',''did'',''didn''''t'',''do'',''does'',''doesn''''t'',''doing'',''don''''t'',''down'',''during'',''each'',''few'',''for'',''from'',''further'',''had'',''hadn''''t'',''has'',''hasn''''t'',''have'',''haven''''t'',''having'',''he'',''he''''d'',''he''''ll'',''he''''s'',''her'',''here'',''here''''s'',''hers'',''herself'',''him'',''himself'',''his'',''how'',''how''''s'',''i'',''i''''d'',''i''''ll'',''i''''m'',''i''''ve'',''if'',''in'',''into'',''is'',''isn''''t'',''it'',''it''''s'',''its'',''itself'',''let''''s'',''me'',''more'',''most'',''mustn''''t'',''my'',''myself'',''no'',''nor'',''not'',''of'',''off'',''on'',''once'',''only'',''or'',''other'',''ought'',''our'',''ours'',''ourselves'',''out'',''over'',''own'',''same'',''shan''''t'',''she'',''she''''d'',''she''''ll'',''she''''s'',''should'',''shouldn''''t'',''so'',''some'',''such'',''than'',''that'',''that''''s'',''the'',''their'',''theirs'',''them'',''themselves'',''then'',''there'',''there''''s'',''these'',''they'',''they''''d'',''they''''ll'',''they''''re'',''they''''ve'',''this'',''those'',''through'',''to'',''too'',''under'',''until'',''up'',''very'',''was'',''wasn''''t'',''we'',''we''''d'',''we''''ll'',''we''''re'',''we''''ve'',''were'',''weren''''t'',''what'',''what''''s'',''when'',''when''''s'',''where'',''where''''s'',''which'',''while'',''who'',''who''''s'',''whom'',''why'',''why''''s'',''with'',''won''''t'',''would'',''wouldn''''t'',''you'',''you''''d'',''you''''ll'',''you''''re'',''you''''ve'',''your'',''yours'',''yourself'',''yourselves''}'::text[];

alter sequence "public"."__raw_logs_id_seq" owned by "public"."__raw_logs"."id";

CREATE UNIQUE INDEX __raw_logs_pkey ON public.__raw_logs USING btree (id);

CREATE UNIQUE INDEX __raw_trends_pkey ON public.__raw_trends USING btree (id);

CREATE UNIQUE INDEX __repo_trends_pkey ON public.repo_trends USING btree (id);

CREATE UNIQUE INDEX legal_documents_pkey ON public.legal_documents USING btree (id);

CREATE UNIQUE INDEX repo_trends_url_key ON public.repo_trends USING btree (url);

alter table "public"."__raw_logs" add constraint "__raw_logs_pkey" PRIMARY KEY using index "__raw_logs_pkey";

alter table "public"."__raw_trends" add constraint "__raw_trends_pkey" PRIMARY KEY using index "__raw_trends_pkey";

alter table "public"."legal_documents" add constraint "legal_documents_pkey" PRIMARY KEY using index "legal_documents_pkey";

alter table "public"."repo_trends" add constraint "__repo_trends_pkey" PRIMARY KEY using index "__repo_trends_pkey";

alter table "public"."legal_documents" add constraint "legal_documents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."legal_documents" validate constraint "legal_documents_user_id_fkey";

alter table "public"."repo_trends" add constraint "__repo_trends___raw_trend_id_fkey" FOREIGN KEY (__raw_trend_id) REFERENCES __raw_trends(id) not valid;

alter table "public"."repo_trends" validate constraint "__repo_trends___raw_trend_id_fkey";

alter table "public"."repo_trends" add constraint "repo_trends_url_key" UNIQUE using index "repo_trends_url_key";

grant delete on table "public"."__raw_logs" to "anon";

grant insert on table "public"."__raw_logs" to "anon";

grant references on table "public"."__raw_logs" to "anon";

grant select on table "public"."__raw_logs" to "anon";

grant trigger on table "public"."__raw_logs" to "anon";

grant truncate on table "public"."__raw_logs" to "anon";

grant update on table "public"."__raw_logs" to "anon";

grant delete on table "public"."__raw_logs" to "authenticated";

grant insert on table "public"."__raw_logs" to "authenticated";

grant references on table "public"."__raw_logs" to "authenticated";

grant select on table "public"."__raw_logs" to "authenticated";

grant trigger on table "public"."__raw_logs" to "authenticated";

grant truncate on table "public"."__raw_logs" to "authenticated";

grant update on table "public"."__raw_logs" to "authenticated";

grant delete on table "public"."__raw_logs" to "service_role";

grant insert on table "public"."__raw_logs" to "service_role";

grant references on table "public"."__raw_logs" to "service_role";

grant select on table "public"."__raw_logs" to "service_role";

grant trigger on table "public"."__raw_logs" to "service_role";

grant truncate on table "public"."__raw_logs" to "service_role";

grant update on table "public"."__raw_logs" to "service_role";

grant delete on table "public"."__raw_trends" to "anon";

grant insert on table "public"."__raw_trends" to "anon";

grant references on table "public"."__raw_trends" to "anon";

grant select on table "public"."__raw_trends" to "anon";

grant trigger on table "public"."__raw_trends" to "anon";

grant truncate on table "public"."__raw_trends" to "anon";

grant update on table "public"."__raw_trends" to "anon";

grant delete on table "public"."__raw_trends" to "authenticated";

grant insert on table "public"."__raw_trends" to "authenticated";

grant references on table "public"."__raw_trends" to "authenticated";

grant select on table "public"."__raw_trends" to "authenticated";

grant trigger on table "public"."__raw_trends" to "authenticated";

grant truncate on table "public"."__raw_trends" to "authenticated";

grant update on table "public"."__raw_trends" to "authenticated";

grant delete on table "public"."__raw_trends" to "service_role";

grant insert on table "public"."__raw_trends" to "service_role";

grant references on table "public"."__raw_trends" to "service_role";

grant select on table "public"."__raw_trends" to "service_role";

grant trigger on table "public"."__raw_trends" to "service_role";

grant truncate on table "public"."__raw_trends" to "service_role";

grant update on table "public"."__raw_trends" to "service_role";

grant delete on table "public"."legal_documents" to "anon";

grant insert on table "public"."legal_documents" to "anon";

grant references on table "public"."legal_documents" to "anon";

grant select on table "public"."legal_documents" to "anon";

grant trigger on table "public"."legal_documents" to "anon";

grant truncate on table "public"."legal_documents" to "anon";

grant update on table "public"."legal_documents" to "anon";

grant delete on table "public"."legal_documents" to "authenticated";

grant insert on table "public"."legal_documents" to "authenticated";

grant references on table "public"."legal_documents" to "authenticated";

grant select on table "public"."legal_documents" to "authenticated";

grant trigger on table "public"."legal_documents" to "authenticated";

grant truncate on table "public"."legal_documents" to "authenticated";

grant update on table "public"."legal_documents" to "authenticated";

grant delete on table "public"."legal_documents" to "service_role";

grant insert on table "public"."legal_documents" to "service_role";

grant references on table "public"."legal_documents" to "service_role";

grant select on table "public"."legal_documents" to "service_role";

grant trigger on table "public"."legal_documents" to "service_role";

grant truncate on table "public"."legal_documents" to "service_role";

grant update on table "public"."legal_documents" to "service_role";

grant delete on table "public"."repo_trends" to "anon";

grant insert on table "public"."repo_trends" to "anon";

grant references on table "public"."repo_trends" to "anon";

grant select on table "public"."repo_trends" to "anon";

grant trigger on table "public"."repo_trends" to "anon";

grant truncate on table "public"."repo_trends" to "anon";

grant update on table "public"."repo_trends" to "anon";

grant delete on table "public"."repo_trends" to "authenticated";

grant insert on table "public"."repo_trends" to "authenticated";

grant references on table "public"."repo_trends" to "authenticated";

grant select on table "public"."repo_trends" to "authenticated";

grant trigger on table "public"."repo_trends" to "authenticated";

grant truncate on table "public"."repo_trends" to "authenticated";

grant update on table "public"."repo_trends" to "authenticated";

grant delete on table "public"."repo_trends" to "service_role";

grant insert on table "public"."repo_trends" to "service_role";

grant references on table "public"."repo_trends" to "service_role";

grant select on table "public"."repo_trends" to "service_role";

grant trigger on table "public"."repo_trends" to "service_role";

grant truncate on table "public"."repo_trends" to "service_role";

grant update on table "public"."repo_trends" to "service_role";


